package kamysh.handler;

public enum ErrorCode {
    ENTRY_NOT_FOUND,
    EXTERNAL_REQUEST_FAILED,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    INCORRECT_ARGUMENT_FORMAT,
    SPACE_MARINE_ALREADY_ON_BOARD,
}
