package kamysh.handler;

public enum ErrorCode {
    ENTRY_NOT_FOUND,
    EXTERNAL_REQUEST_FAILED,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    INCORRECT_ARGUMENT_FORMAT,
    REMOTE_SERVICE_UNAVAILABLE,
    STORAGE_SERVICE_REQUEST_FAILED,
}
